version: "3.8"

services:
    database:
        image: mysql:latest
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: adminadmin
            MYSQL_DATABASE: laravel-jwt
            MYSQL_USER: adminadmin
            MYSQL_PASSWORD: adminadmin
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
